### PR TITLE
alluvial.R accepts colour data.frame

### PR DESCRIPTION
**Pull request by FabianGrammes**
Allows individual coloring of the ribbons. 

Example: 

``` R
library(alluvial)
library(dplyr)

tit <- tibble::as_data_frame(Titanic)

col <- tit %>%
    dplyr::transmute(col1 = "grey",
                     col2 = ifelse(Sex == "Female","magenta","steelblue"),
                     col3 = ifelse(Age == "Child","green","grey"),
                     col4 = ifelse(Survived == "No","red","green")) %>%
                         as.data.frame()

alluvial( select(tit, Survived, Sex, Age, Class),
            freq=tit$n,
            col = col,
            layer = tit$Survived != "Yes",
            alpha = 0.3,
            blocks=TRUE)

```

### CODE REVIEW

**Comment by mbojan** [comment]
Thanks! Very nice!

Can you have a look why the tests fail in your branch?

**Comment by FabianGrammes** [comment]
Sure,

I'll fix that later today and send a new pull request

**Comment by FabianGrammes** [comment]
Ok fixed, issue was using numbers as colors ...

**Comment by mbojan** [comment]
Thanks!

**Comment by mbojan** [comment]
I had to revert this merge as it is not backward compatible. Try running the examples of `alluvial` and please check if stripes are of proper colors.

**Comment by FabianGrammes** [comment]
Alright, I'll check things more thorough and get back to you at a later time. 

cheers, F

**Pull request merged**
