### PR TITLE
use 'hide' column in p rather than raw input to exclude ribbons

### PR DESCRIPTION
**Pull request by corybrunson**
When using `layer` and `hide` together, i noticed that non-standard `layer`s would result in the wrong ribbons being omitted. This was because the `hide` input was being used after invoking `order`. Instead, i've used the `hide` column in `p` before using `order`, which solved the problem in some examples i used. A `check()` produced no errors and the documentation did not change.

### CODE REVIEW

**Comment by mbojan** [comment]
Thanks, but can you show me an example in which the current version does not work as expected?

**Comment by corybrunson** [comment]
Oh, thanks for clarifying (again). I'll construct an example and post it as an issue.

**Comment by mbojan** [comment]
Something is not right with your fix. Below wrong ribbon is being hidden.

```
d <- data.frame(
  x = c(1, 2, 3),
  y = c(3 ,2, 1),
  freq=c(1,1,1)
)

# Trying to hide 2-2
alluvial(d[,1:2], freq=d$freq, col=1:3, alpha=1,
         hide=d$x == 2)
# hides 3-1 instead
```

**Comment by corybrunson** [comment]
Yes, sorry about that. In addition to forgetting the `p$` before `hide`, i failed to notice that `order()` converted the row indices to contiguous positions; the container `which(!p$hide)[]` now corrects for this. It isn't particularly elegant, but the other solution that occurs to me—using `intersect()` or `setdiff()`—would be less so.

**Pull request merged**
